# Generated by Django 5.1.3 on 2025-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_studentanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ManyToManyField(to='api.course'),
        ),
    ]
