# Generated by Django 5.1.2 on 2025-03-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_answer_id_remove_question_id_remove_quiz_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer', to='api.quiz'),
        ),
    ]
